[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hexio"
version = "0.0.4"
description = "Utility package to handle I/O of hex-compatible data."
requires-python = ">=3.9"
dependencies = [
  "pytest",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/valbucci/hexio"
Issues = "https://github.com/valbucci/hexio/issues"
